### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by palb91** [tadeokondrak/waypoint#1]
Hello, I see that the last commit is two years old.
Your tool works! It already helped me a lot, would you consider updating it?
I'm not a developper myself so I won't be helpful in this way, but I can participate from a user point of view.
I have seen several times people asking for a keynav replacement for Wayland and here is your tool, so there would be a public.

**Comment by tadeokondrak** [comment]
Nice to hear that it's been helpful! I am interested in updating the code and using this myself.
Are there any specific features/fixes you'd like to see in waypoint?
I'd like to fix the crashes on the pointer going off-screen, and add better configuration and multi-monitor support.

**Comment by palb91** [comment]
Nice!

I term of issues, there is effectively the pointer going off-screen (which can be easily avoided), but the issue that is more annoying is in multi-monitor setup, the grid only works in only one monitor.

I term of features,  what I miss from keynav is:
* a configuration file (I use a bépo keyboard — sort of dvorak for French — and I was able to modify the code for using my own keys, but a configuration file would help to extend a bit waypoint (bindings, default grid, maybe macros, why not colors);
* undoing last cuts/moves, so it needs an history;
* press/release click for drag'n'drop (I was able to implement it, but it is a bit buggy);
* right click and maybe other mouse controls (middle click, scrolling);
* a man/help once more things are implemented.

What do you think about this first list?

**Comment by hendursaga** [comment]
First off, thanks for beating me to creating this! I've tried [this clone](https://github.com/gabcoh/keynav-wayland) and [warpd](https://github.com/rvaiya/warpd) and yours is the simplest. (warpd also supports X11 and has other unneeded functionality, but that's beside the point.)

My list of improvements would start with:

1) The pointer going off-screen.
2) Configuration file, preferably in a format that won't pull in more dependencies.
3) History.
4) "Hinting" support.
5) Other mouse controls.
6) More documentation.

**Comment by tadeokondrak** [comment]
Thanks for the feedback! I've implemented a few things.

There's a configuration file now, but keybind support is currently limited to single keys and not combinations.

Drag-and-drop is really buggy if implemented naively so I haven't added that yet. Need to find the proper way to do it.

**Comment by vincentaxhe** [comment]
I hope can locate pointer than cut from whole,always drag pointer with it, multi monitor support is of high priority.

**Comment by tadeokondrak** [comment]
Issues here have been moved to individual other tickets
